In [1]:
import numpy as np #Numpy is time & space-efficient multidimensional arrays

In [2]:
numpy_array = np.array([1,2,3]) #1D array

In [3]:
print(type(numpy_array))

<type 'numpy.ndarray'>


In [4]:
print(numpy_array.shape)

(3L,)


In [5]:
print(numpy_array[1])

2


In [6]:
numpy_array[0] = 4

In [7]:
print(numpy_array)

[4 2 3]


In [8]:
vijay = np.array([[1,2,3],[4,5,6]]) #2D array

In [9]:
print(vijay)

[[1 2 3]
 [4 5 6]]


In [10]:
print(vijay.shape)

(2L, 3L)


In [11]:
rag = np.zeros((2,2)) #Zero matrix

In [12]:
print(rag)

[[0. 0.]
 [0. 0.]]


In [20]:
one = np.ones((2,3)) #One matrix

In [14]:
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
identity = np.eye(3,3) #Identity matrix

In [16]:
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
np.random.random((2,2))

array([[0.90109554, 0.59803443],
       [0.63234288, 0.10543253]])

In [24]:
np.random.randint(3,9)

5

In [37]:
vjr = np.array([[1,2,3,5],[3,5,6,7],[6,7,2,8]])

In [38]:
print(vjr)

[[1 2 3 5]
 [3 5 6 7]
 [6 7 2 8]]


In [39]:
print(vjr.shape)

(3L, 4L)


In [40]:
sliced = vjr[:2,2:] #1st co-ordinate is row & 2nd co-ordinate is column

In [41]:
print(sliced)

[[3 5]
 [6 7]]


In [42]:
vjr[1,2] #here it's value is 5

6

In [43]:
sliced[1,0]=1000

In [44]:
vjr[1,2] #here it's value is 1000 because the value is sliced and the value is changed too!

1000

In [45]:
raghav = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(raghav)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
row_array = raghav[1,:]
Row_array = raghav[1:2,:]
print(row_array,row_array.shape)
print(Row_array,Row_array.shape)

(array([5, 6, 7, 8]), (4L,))
(array([[5, 6, 7, 8]]), (1L, 4L))


In [11]:
col_array = raghav[:,1]
Col_array =raghav[:,1:2]
print(col_array,col_array.shape)
print(Col_array,Col_array.shape)

(array([ 2,  6, 10]), (3L,))
(array([[ 2],
       [ 6],
       [10]]), (3L, 1L))


In [12]:
row_indices = np.array([0,1,2,0])
col_indices = np.arange(4)

In [16]:
for row,col in zip(row_indices, col_indices):
    print(row,col)

(0, 0)
(1, 1)
(2, 2)
(0, 3)


In [18]:
print(raghav[row_indices,col_indices])

[ 1  6 11  4]


In [19]:
raghav[row_indices,col_indices]+=1000
print(raghav)

[[1001    2    3 1004]
 [   5 1006    7    8]
 [   9   10 1011   12]]


In [20]:
vj = np.array([[11,12],[21,22],[31,32]])
print(vj)

[[11 12]
 [21 22]
 [31 32]]


In [21]:
filter = (vj > 15)
print(filter)

[[False False]
 [ True  True]
 [ True  True]]


In [23]:
print(vj[filter])#Displaing the elements which meets the criteria

[21 22 31 32]


In [24]:
vj[(vj % 2 == 0)]#It show the only elment that are even.The condition can be given in the position of the array.

array([12, 22, 32])

In [25]:
vj[(vj % 2 == 0)] += 1000
print(vj) # By filtering and also we can add values to to the filtered items.

[[  11 1012]
 [  21 1022]
 [  31 1032]]


In [26]:
ex1 = np.array([11,12]) #Python assigns the datatype
print(ex1.dtype)

int32


In [3]:
ex2 = np.array([2.4,4.7],dtype = np.int64)
print(ex2.dtype)
print(ex2)

int64
[2 4]


In [29]:
ex3 = np.array([8,9],dtype=np.float64)
print(ex3) # We can also assign the 

[8. 9.]


In [33]:
x = np.array([[111,112],[121,122]],dtype = np.int)
y = np.array([[211.1,212.1],[221.1,222.1]],dtype = np.float64)

print(x)
print("\n")
print(y)

[[111 112]
 [121 122]]


[[211.1 212.1]
 [221.1 222.1]]


In [34]:
print(x+y) #Adding content inside the elements

[[322.1 324.1]
 [342.1 344.1]]


In [35]:
print(np.add(x,y))#Adding using add function

[[322.1 324.1]
 [342.1 344.1]]


In [36]:
print(np.subtract(x,y))# Subracting using subract function

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [37]:
print(np.multiply(x,y)) #Multiply using multiply function

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [38]:
print(np.sqrt(x)) #Finding Square root function using sqrt function

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [39]:
print(np.exp(x)) #Finding Exponentitation function using exp function.

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [2]:
arr = 50 * np.random.randn(2,5) #Generating random elements as an array
print(arr)

[[ 33.31494236  85.54234245  36.38171512  23.38583366  39.87937296]
 [ -5.93613617 -77.45315586  77.73502953   2.59140206 -68.69718203]]


In [3]:
print(arr.mean()) 

14.674416408141548


In [4]:
print(arr.mean(axis = 1))#Axis = 1 will represent the mean according to row-wise.

[ 43.70084131 -14.35200849]


In [5]:
print(arr.mean(axis = 0)) #Axis = 0 will represent the mean according to column-wise.

[ 13.68940309   4.04459329  57.05837233  12.98861786 -14.40890453]


In [56]:
print(arr.sum()) #Sum of whole array  elements

1.8078559282229874


In [51]:
unsorted = np.random.randn(10)
print(unsorted)

[-2.13067186  0.69980634 -0.55394348  1.45564394 -0.08612036  0.46065355
 -0.53507479  0.03270211 -0.38523982 -0.24801222]


In [53]:
sorted = np.array(unsorted)
sorted.sort() #Using sort function.
print(sorted)

[-2.13067186 -0.55394348 -0.53507479 -0.38523982 -0.24801222 -0.08612036
  0.03270211  0.46065355  0.69980634  1.45564394]


In [55]:
unsorted.sort()
print(unsorted)

[-2.13067186 -0.55394348 -0.53507479 -0.38523982 -0.24801222 -0.08612036
  0.03270211  0.46065355  0.69980634  1.45564394]


In [59]:
car = np.array([1,3,1,2,9,3,9])
print(np.unique(car))#Finding Unique element

[1 2 3 9]


In [64]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1)
print(s2)#Declaring a set of strings in s1 array

['desk' 'chair' 'bulb']
['lamp' 'bulb' 'chair']


In [65]:
print(np.intersect1d(s1,s2)) #Intersection of two arrays using intersect1d

['bulb' 'chair']


In [66]:
print(np.union1d(s1,s2)) #Union of two arrays using union1d

['bulb' 'chair' 'desk' 'lamp']


In [67]:
print(np.setdiff1d(s1,s2)) #Setdifference of two arrays using setdiff1d

['desk']


In [68]:
print(np.in1d(s1,s2)) #To check whether the elememnt in s1 is found in s2.

[False  True  True]


In [8]:
start = np.zeros((3,3))

In [9]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
add = [1,2,3]
print(add)

[1, 2, 3]


In [12]:
y = start + add
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [13]:
add_1 = np.array([1,2,3])

In [14]:
z = start + add_1
print(z)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [20]:
w = np.array([[3,4,5]])
w = w.T
print(w)

[[3]
 [4]
 [5]]


In [21]:
f = start + w
print(f)

[[3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]


In [25]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits= 1000

In [26]:
nd_array = arange(size)
print(type(nd_array))

<type 'numpy.ndarray'>


In [28]:
timer_numpy = Timer("nd_array.sum()","from __main__ import nd_array")

print("Time taken for the excecution is %f seconds" %(timer_numpy.timeit(timeits)/timeits))

Time taken for the excecution is 0.000465 seconds


In [29]:
a_list = list(range(size))
print(type(a_list))

<type 'list'>


In [31]:
timer_list = Timer("sum(a_list)","from __main__ import a_list")

print("Time taken to run: %f seconds" %(timer_list.timeit(timeits)/timeits))

Time taken to run: 0.054287 seconds


In [32]:
x = np.array([15.15, 20.20])

In [33]:
np.save('vijay',x)   #Writing to the disk

In [34]:
np.load('vijay.npy')    #loading from the disk

array([15.15, 20.2 ])

In [35]:
np.savetxt('array.txt',X=x,delimiter=',')

In [36]:
np.loadtxt('array.txt',delimiter = ',')

array([15.15, 20.2 ])

In [37]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

In [39]:
print(x2d.dot(y2d)) #Multiplication of two matrices

[[4 4]
 [4 4]]


In [40]:
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]


In [41]:
a1d = np.array([9,9])
a2d = np.array([10,10])
print(a1d.dot(a2d)) # Multiplication of two vectors.

180


In [42]:
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))

66


In [44]:
print(np.sum(ex1, axis = 1))  # Sum value according to row-wise

[23 43]


In [45]:
print(np.sum(ex1, axis = 0))   # Sum value according to column-wise

[32 34]


In [48]:
v = np.random.randn(8)
v

array([-0.39935936, -0.46563433,  0.2551324 , -0.70333377, -0.82480608,
       -0.97137023,  0.00183971, -1.46745479])

In [49]:
y = np.random.randn(8)
y

array([-1.00916306,  1.386776  ,  0.44082901,  1.00848415, -1.18752773,
        0.95825295,  0.38333901, -0.14370418])

In [50]:
np.maximum(v,y) # Returns the maximum element between two arrays.

array([-0.39935936,  1.386776  ,  0.44082901,  1.00848415, -0.82480608,
        0.95825295,  0.38333901, -0.14370418])

In [53]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [56]:
arr.reshape(10,2)  # Reshaping the matrix

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [59]:
k = np.random.randint(low = 2, high = 50, size=(2,2))
k

array([[ 2, 35],
       [33, 23]])

In [70]:
s = np.random.randint(low = 2, high = 50, size=(2,2))
s

array([[48, 18],
       [22, 31]])

In [63]:
np.vstack((k,s)) #Adding Vetically

array([[ 2, 35],
       [33, 23],
       [13, 22],
       [24,  5]])

In [65]:
np.hstack((k,s))   #Adding Horizontally

array([[ 2, 35, 13, 22],
       [33, 23, 24,  5]])

In [66]:
np.concatenate([k,s],axis = 0) #Concatenate vertically

array([[ 2, 35],
       [33, 23],
       [13, 22],
       [24,  5]])

In [67]:
np.concatenate([k,s], axis = 1) #Concatenate Horoi

array([[ 2, 35, 13, 22],
       [33, 23, 24,  5]])

In [71]:
x1 = np.array([1,2,3,4,5])

x2 = np.array([11,12,33,44,55])

filter = np.array([True, False, True, False, True])

In [74]:
out = np.where(filter,x1,x2)
out

array([ 1, 12,  3, 44,  5])

In [76]:
mat = np.random.rand(5,5)
mat

array([[0.1770274 , 0.40427489, 0.68956558, 0.18542503, 0.84459986],
       [0.03234281, 0.14074836, 0.80053447, 0.05356585, 0.84595711],
       [0.30416718, 0.37282314, 0.79624381, 0.06792497, 0.09531109],
       [0.12232095, 0.39843979, 0.34725967, 0.10362128, 0.56750463],
       [0.82837196, 0.27019559, 0.26562241, 0.9394277 , 0.63527264]])

In [78]:
np.where(mat > 0.4, 1001, -1)

array([[  -1, 1001, 1001,   -1, 1001],
       [  -1,   -1, 1001,   -1, 1001],
       [  -1,   -1, 1001,   -1,   -1],
       [  -1,   -1,   -1,   -1, 1001],
       [1001,   -1,   -1, 1001, 1001]])

In [85]:
y = np.random.normal(size = (1,5))[0]
print(y)

[-0.9566346   0.76902049 -0.47730528  2.52375656  0.45231257]


In [89]:
z = np.random.randint(low = 2, high = 50, size = 4)
z

array([ 6, 16, 13, 28])

In [90]:
np.random.permutation(z) #Return a new ordering of elements in z

array([13,  6, 16, 28])

In [91]:
np.random.uniform(size = 4)

array([0.0033189 , 0.20314153, 0.86030637, 0.51871157])

In [92]:
np.random.normal(size = 4)

array([-0.06441547, -2.33452418,  0.05275814, -0.621286  ])

In [93]:
l = [1,2,3]
x1 = np.array(l)

In [94]:
print(type(x1),x1)

(<type 'numpy.ndarray'>, array([1, 2, 3]))


In [102]:
print("Dimensionality of the array :",x1.ndim)  #Dimensionality is given by ndim

('Dimensionality of the array :', 1)


In [110]:
x1 = np.array([[2],[5],[8]])
x2 = np.array([[1,3,6]])
print(x1)
print(x2)

[[2]
 [5]
 [8]]
[[1 3 6]]


In [112]:
print(np.dot(x1,x2))

[[ 2  6 12]
 [ 5 15 30]
 [ 8 24 48]]


In [117]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
np.dot(m1,m2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])